version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: shortlink-postgres
    environment:
      POSTGRES_DB: shortlink
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  app:
    build: .
    container_name: shortlink-app
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/shortlink
      NEXT_PUBLIC_BASE_URL: http://localhost:3000
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
